source: src

plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock

title: adryd
email: me@adryd.com
baseurl: ""
url: "https://adryd.com"
permalink: "pages/:title/"
